### ISSUE TITLE
Documentation step 8 changes

### ISSUE THREAD

**Issue by adpe** [maths/stack_util_maximapool#31]
Hi @sangwinc  

IMO here should be adapted two lines more (e.g example):
- file_search_maxima:append([sconcat("`/var/www/html/moodle/question/type/stack/stack`/maxima/###.{mac,mc}")] , file_search_maxima)$

- file_search_lisp:append([sconcat("`/var/www/html/moodle/question/type/stack/stack`/maxima/###.{lisp}")] , file_search_lisp)$

Should point to the **MaximaPool paths**:
- file_search_maxima:append([sconcat("`$MAXIMAPOOL/%%VERSION%%`/maxima/###.{mac,mc}")] , file_search_maxima)$
- file_search_lisp:append( [sconcat("`$MAXIMAPOOL/%%VERSION%%`/maxima/###.{lisp}")] , file_search_lisp)$

As the files are copied 1:1 to the $MAXIMAPOOL, they can get retrieved here and not in the www-directory. I had permission problems and I don't want to give to the `tomcat` user access to the www-directory.

Thanks
Adrian

**Comment by aharjula** [comment]
Maybe permuting steps 6-8 so that the paths in step 6 can be tied to the `maximalocal.mac` modifications in step 8 and the acquisition of that file in step 7.

But yes that path tuning is indeed something people do and I for one have always done but for some reason it is missing from the documentation.

Note that if you are logged in to GitHub you should be able to simply edit the documentation from the icon at the right hand corner of the documentation box. It will then allow you to either create a pull request for that change or direct commit if you have enough rights.

**Comment by adpe** [comment]
Thank you @aharjula - I closed the issue.
